name: teach_rate
description: CTSE Mobile Application
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_rating_stars: ^1.0.3+4
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  http: ^0.13.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
